// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbWZpwcTVs4KwQYPBvFOn27X0-62wDfZw',
    appId: '1:408873652483:web:10ae948a34cc0d14525936',
    messagingSenderId: '408873652483',
    projectId: 'gimnasio-4d423',
    authDomain: 'gimnasio-4d423.firebaseapp.com',
    databaseURL: 'https://gimnasio-4d423-default-rtdb.firebaseio.com',
    storageBucket: 'gimnasio-4d423.firebasestorage.app',
    measurementId: 'G-PVVNW290ET',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxgP93VMCYzAEpIPlaaEO7EvswXSBfdCY',
    appId: '1:408873652483:android:026469968773614e525936',
    messagingSenderId: '408873652483',
    projectId: 'gimnasio-4d423',
    databaseURL: 'https://gimnasio-4d423-default-rtdb.firebaseio.com',
    storageBucket: 'gimnasio-4d423.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb0kBXfqvcRH6ktqztscZCyx3qmSuCTFQ',
    appId: '1:408873652483:ios:91f25a5d88f89d1f525936',
    messagingSenderId: '408873652483',
    projectId: 'gimnasio-4d423',
    databaseURL: 'https://gimnasio-4d423-default-rtdb.firebaseio.com',
    storageBucket: 'gimnasio-4d423.firebasestorage.app',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCbWZpwcTVs4KwQYPBvFOn27X0-62wDfZw',
    appId: '1:408873652483:web:c106b485d3901839525936',
    messagingSenderId: '408873652483',
    projectId: 'gimnasio-4d423',
    authDomain: 'gimnasio-4d423.firebaseapp.com',
    databaseURL: 'https://gimnasio-4d423-default-rtdb.firebaseio.com',
    storageBucket: 'gimnasio-4d423.firebasestorage.app',
    measurementId: 'G-432WY7H4RQ',
  );
}
